"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.USER_PRESENCE_INTERVAL = exports.MAX_TITLE_LENGTH = exports.MAX_AVATAR_DISPLAY = void 0;
var USER_PRESENCE_INTERVAL = 5000;
exports.USER_PRESENCE_INTERVAL = USER_PRESENCE_INTERVAL;
var MAX_AVATAR_DISPLAY = 6;
exports.MAX_AVATAR_DISPLAY = MAX_AVATAR_DISPLAY;
var MAX_TITLE_LENGTH = 100;
exports.MAX_TITLE_LENGTH = MAX_TITLE_LENGTH;